export const START_FETCHING_CATEGORY = "redux/category/START_FETCHING_CATEGORY";
export const SUCCESS_FETCHING_CATEGORY =
  "redux/category/SUCCESS_FETCHING_CATEGORY";
export const ERROR_FETCHING_CATEGORY = "redux/category/ERROR_FETCHING_CATEGORY";
