export const START_FETCHING_LIST_CATEGORY =
  "redux/list/START_FETCHING_LIST_CATEGORY";
export const SUCCESS_FETCHING_LIST_CATEGORY =
  "redux/list/SUCCESS_FETCHING_LIST_CATEGORY";
export const ERROR_FETCHING_LIST_CATEGORY =
  "redux/list/ERROR_FETCHING_LIST_CATEGORY";

export const START_FETCHING_LIST_SPEAKER =
  "redux/list/START_FETCHING_LIST_SPEAKER";
export const SUCCESS_FETCHING_LIST_SPEAKER =
  "redux/list/SUCCESS_FETCHING_LIST_SPEAKER";
export const ERROR_FETCHING_LIST_SPEAKER =
  "redux/list/ERROR_FETCHING_LIST_SPEAKER";
